# Generated by Django 5.1.5 on 2025-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sem_budget', models.DecimalField(decimal_places=2, help_text='Current semester aid budget in MYR', max_digits=12)),
                ('total_aid_balance', models.DecimalField(decimal_places=2, help_text='Total aid account balance in MYR', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
            ],
        ),
    ]
