# Generated by Django 5.1.5 on 2025-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinformation',
            name='most_recent_subtraction',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='temporary storage of last transaction', max_digits=12),
            preserve_default=False,
        ),
    ]
