# Generated by Django 5.1.5 on 2025-02-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('app_type', models.CharField(choices=[('Financial', 'Financial'), ('Tuition Reduction', 'Tuition Reduction'), ('Food', 'Food'), ('Study Supplies', 'Study Supplies'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
                ('app_date', models.DateField()),
                ('app_description', models.TextField(max_length=1000)),
                ('app_attached1', models.BinaryField(blank=True, null=True)),
                ('app_attached2', models.BinaryField(blank=True, null=True)),
                ('app_attached3', models.BinaryField(blank=True, null=True)),
                ('app_attached4', models.BinaryField(blank=True, null=True)),
                ('app_attached5', models.BinaryField(blank=True, null=True)),
                ('app_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Appealing', 'Appealing')], default='Pending', max_length=10)),
                ('forwarded_to_finance', models.BooleanField(default=False)),
                ('app_denyreason', models.TextField(blank=True, max_length=1000, null=True)),
                ('app_denyreason2', models.TextField(blank=True, max_length=1000, null=True)),
                ('app_appeal', models.TextField(blank=True, max_length=1000, null=True)),
                ('app_appealdate', models.DateField(blank=True, null=True)),
                ('app_decider', models.CharField(blank=True, max_length=10, null=True)),
                ('app_decider2', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
