# Generated by Django 5.1.5 on 2025-02-05 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidRecipients',
            fields=[
                ('aid_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aid_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Concluded', 'Concluded')], max_length=10)),
                ('aid_type', models.CharField(choices=[('Financial', 'Financial'), ('Tuition Reduction', 'Tuition Reduction'), ('Food', 'Food'), ('Study Supplies', 'Study Supplies'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
                ('aid_desc', models.TextField(max_length=1000)),
                ('aid_changereason', models.TextField(blank=True, max_length=1000, null=True)),
                ('aid_changedecider', models.CharField(blank=True, max_length=10, null=True)),
                ('aid_changedate', models.DateField(blank=True, null=True)),
                ('aid_startdate', models.DateField()),
                ('aid_enddate', models.DateField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_recipients', to='home.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aid_recipients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
