# Generated by Django 5.1.5 on 2025-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrecipients',
            name='aid_amount',
            field=models.IntegerField(null=True),
        ),
    ]
