# Generated by Django 5.1.5 on 2025-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_management', '0002_aidrecipients_aid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrecipients',
            name='aid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
