# Generated by Django 5.1.5 on 2025-02-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid_management', '0004_alter_aidrecipients_aid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidrecipients',
            name='aid_amount',
        ),
    ]
